# Netlify configuration for MagicNook

[build.environment]
  # This is a temporary measure to disable secret scanning.
  # This is not recommended for production, but is used here to
  # unblock the build process.
  SECRETS_SCAN_ENABLED = "false"
